import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AuthProvider from "@/components/AuthProvider/AuthProvider";
import GoogleAnalytics from "@/components/GoogleAnalytics/GoogleAnalytics";
import Header from "@/components/Header/Header";
import "./globals.scss";
import CookieBanner from "@/components/GoogleAnalytics/CookieBanner";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "GIPHY - Be Animated",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="mx-auto max-w-[1040px]">
      <AuthProvider>
        <GoogleAnalytics GA_MEASUREMENT_ID="G-WN680W2WNK" />
        <Toaster position="top-center" reverseOrder={false} />
        <body className={inter.className}>
          <Header />
          {children}
          <CookieBanner />
        </body>
      </AuthProvider>
    </html>
  );
}
